/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: import.meta.env.VITE_AWS_PROJECT_REGION,
  aws_appsync_graphqlEndpoint: import.meta.env
    .VITE_AWS_APPSYNC_GRAPHQL_ENDPOINT,
  aws_appsync_region: import.meta.env.VITE_AWS_PROJECT_REGION,
  aws_appsync_authenticationType: import.meta.env
    .VITE_AWS_APPSYNC_AUTHENTICATIONTYPE,
  aws_appsync_apiKey: import.meta.env.VITE_AWS_APPSYNC_API_KEY,
  aws_cognito_identity_pool_id: VITE_AWS_POOL_ID,
  aws_cognito_region: import.meta.env.VITE_AWS_PROJECT_REGION,
  aws_user_pools_id: import.meta.env.VITE_AWS_USERPOOL_ID,
  aws_user_pools_web_client_id: import.meta.env.VITE_AWS_USERPOOL_WEB_CLIENT,
  oauth: import.meta.env.VITE_OAUTH,
  aws_cognito_username_attributes: import.meta.env.VITE_CONGNITO_USER_ATTRIBUTE,
  aws_cognito_social_providers: import.meta.env.VITE_COGNITO_SOCIAL_PROVIDER,
  aws_cognito_signup_attributes: import.meta.env
    .VITE_AWS_COGNITO_SIGNUP_ATTRIBUTE,
  aws_cognito_mfa_configuration: import.meta.env.VITE_AWS_MFA_CONFIGURATION,
  aws_cognito_mfa_types: import.meta.env.VITE_AWS_MFA_CONFIGURATION_TYPE,
  aws_cognito_password_protection_settings: import.meta.env
    .VITE_AWS_COGNITO_PASSWORD_PROTACTION,
  aws_cognito_verification_mechanisms: import.meta.env
    .VITE_AWS_COGNITO_VERIFICATION_MECHANISM,
  aws_user_files_s3_bucket: import.meta.env.VITE_AWS_S3_BUCKETNAME,
  aws_user_files_s3_bucket_region: import.meta.env.VITE_AWS_PROJECT_REGION,
};

export default awsmobile;
